bits 16
segment _TEXT public class=CODE use16

%macro gate 1
global %1
%1: int 0x83
%endmacro

gate MessageBox
gate InitApp
gate PostQuitMessage
gate SetTimer
gate KillTimer
gate GetCurrentTime
gate ClipCursor
gate GetCursorPos
gate SetCapture
gate ReleaseCapture
gate SetFocus
gate GetFocus
gate RemoveProp
gate GetProp
gate SetProp
gate ClientToScreen
gate ScreenToClient
gate IsIconic
gate GetWindowRect
gate GetClientRect
gate EnableWindow
gate IsWindowEnabled
gate GetWindowText
gate SetWindowText
gate BeginPaint
gate EndPaint
gate CreateWindow
gate ShowWindow
gate BringWindowToTop
gate GetParent
gate IsWindow
gate FindWindow
gate DestroyWindow
gate MoveWindow
gate RegisterClass
gate GetActiveWindow
gate ScrollWindow
gate SetScrollPos
gate SetScrollRange
gate GetDC
gate ReleaseDC
gate SetCursor
gate SetCursorPos
gate ShowCursor
gate SetRect
gate CopyRect
gate PtInRect
gate OffsetRect
gate InflateRect
gate IntersectRect
gate FillRect
gate FrameRect
gate DrawIcon
gate DrawText
gate DialogBox
gate EndDialog
gate GetDlgItem
gate SetDlgItemText
gate GetDlgItemText
gate SetDlgItemInt
gate GetDlgItemInt
gate CheckRadioButton
gate CheckDlgButton
gate IsDlgButtonChecked
gate DlgDirList
gate SendDlgItemMessage
gate MessageBeep
gate GetKeyState
gate DefWindowProc
gate GetMessage
gate PeekMessage
gate PostMessage
gate SendMessage
gate TranslateMessage
gate DispatchMessage
gate RegisterWindowMessage
gate CallWindowProc
gate UpdateWindow
gate InvalidateRect
gate ValidateRect
gate GetClassLong
gate GetWindowWord
gate SetWindowWord
gate GetWindowLong
gate SetWindowLong
gate LoadMenu
gate CreateMenu
gate DestroyMenu
gate ChangeMenu
gate CheckMenuItem
gate EnableMenuItem
gate GetSystemMenu
gate GetMenu
gate SetMenu
gate GetSubMenu
gate DrawMenuBar
gate WinHelp
gate LoadCursor
gate LoadIcon
gate LoadBitmap
gate LoadString
gate LoadAccelerators
gate TranslateAccelerator
gate GetSystemMetrics
gate GetSysColor
gate GrayString
gate GetSysModalWindow
gate ChildWindowFromPoint
gate TabbedTextOut
gate GetTopWindow
gate SetWindowPos
gate GetCapture
gate DialogBoxIndirectParam
gate CreateDialogIndirectParam
gate EqualRect
gate GetAsyncKeyState
gate GetDlgCtrlID
gate SelectPalette
gate RealizePalette
gate GetDesktopWindow
gate GetLastActivePopup
gate CreateIcon
gate InsertMenu
gate AppendMenu
gate RemoveMenu
gate DeleteMenu
gate ModifyMenu
gate wsprintf
gate lstrcmp
gate AnsiUpper
gate AnsiLower
gate DestroyIcon
gate DrawFocusRect
gate lstrcmpi
gate AnsiNext
gate WNetGetConnection
gate RetroWndProcReturn
