load("@rules_nasm//nasm:defs.bzl", "nasm_library")
load("//toolchain:os2_watcom.bzl", "os2_dll")

nasm_library(
    name = "doscalls_obj",
    srcs = ["doscalls.asm"],
    copts = ["-fobj"],
)

os2_dll(
    name = "doscalls_dll",
    obj = ":doscalls_obj",
    out = "DOSCALLS.DLL",
    module_name = "DOSCALLS",
    exports = [
        "DosQueryMem.306",

        "DosError.212",
        "DosSetFileInfo.218",
        "DosSetPathInfo.219",
        "DosSetDefaultDisk.220",
        "DosSetFSInfo.222",
        "DosQueryPathInfo.223",
        "DosDeleteDir.226",
        "DosSleep.229",
        "DosKillProcess.235",
        "DosSetCurrentDir.255",
        "DosCopy.258",
        "DosDelete.259",
        "DosDupHandle.260",
        "DosFindClose.263",
        "DosFindFirst.264",
        "DosFindNext.265",
        "DosCreateDir.270",
        "DosMove.271",
        "DosSetFileSize.272",
        "DosQueryCurrentDir.274",
        "DosQueryCurrentDisk.275",
        "DosQueryFSAttach.277",
        "DosQueryFSInfo.278",
        "DosQueryFileInfo.279",
        "DosExecPgm.283",
        "DosDevIOCtl.284",
        "DosBeep.286",
        "DosSetMem.305",
        "DosLoadModule.318",
        "DosQueryModuleName.320",
        "DosFreeModule.322",
        "DosQueryAppType.323",
        "DosGetResource.352",
        "DosFreeResource.353",
        "DosRaiseException.356",
        "DosUnwindException.357",
        "DosEnumAttribute.372",
        "DosSetSignalExceptionFocus.378",

        "DosQueryHType.224",
        "DosGetDateTime.230",
        "DosExit.234",
        "DosResetBuffer.254",
        "DosSetFilePtr.256",
        "DosClose.257",
        "DosOpen.273",
        "DosRead.281",
        "DosWrite.282",
        "DosQueryCp.291",
        "DosAllocMem.299",
        "DosAllocSharedMem.300",
        "DosGetNamedSharedMem.301",
        "DosFreeMem.304",
        "DosGetInfoBlocks.312",
        "DosQueryModuleHandle.319",
        "DosQueryProcAddr.321",
        "DosQuerySysInfo.348",
        "DosSetRelMaxFH.382",
        "DosFlatToSel.425",
        "DosSelToFlat.426",
        "DosOpenL.981",
        "DosSetFileLocksL.986",
        "DosSetFilePtrL.988",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "doscalls_sources",
    srcs = ["doscalls.asm"],
    visibility = ["//visibility:public"],
)
