//! OSD mount setup: stage drive/access choices and export a boot configuration.
use crate::kernel::{
    fs::disk::FilesystemVolume,
    mount_config::{self, Access, Config, Mount},
    vfs,
};
use alloc::{boxed::Box, string::String, vec::Vec};
use mount_config::{open, prefix, uuid, uuid_text};

// The mount editor stages configuration; it never changes active drive mappings.
// Export is the sole write action and uses the ordinary VFS permission checks.
struct EditorVolume {
    volume: FilesystemVolume,
    home: Vec<u8>,
    id: String,
    label: String,
    selected: Option<Mount>,
    original_name: Option<String>,
    mounted: Option<&'static [u8]>,
    volatile: bool,
}
struct Editor {
    volumes: Vec<EditorVolume>,
    config: Option<Config>,
    settings: String,
    protected: bool,
    destination: usize,
    status: String,
}
// Like Vfs/BackingFile, this state is used by the single kernel event loop.
// No interrupt accesses it and filesystem operations are serialized by VFS.
unsafe impl Send for Editor {}
static EDITOR: spin::Mutex<Editor> = spin::Mutex::new(Editor {
    volumes: Vec::new(),
    config: None,
    settings: String::new(),
    protected: false,
    destination: 0,
    status: String::new(),
});

pub fn init_editor(volumes: &[FilesystemVolume], config: &Config, boot: &crate::BootConfig) {
    let mut editor = EDITOR.lock();
    editor.volumes.clear();
    editor.destination = 0;
    editor.protected = boot.ram_overlay;
    editor.config = Some(config.clone());
    editor.settings = String::from("# Generated by RetroOS mount editor\n");
    if let Some(bundle) = &config.bundle {
        editor.settings.push_str(&alloc::format!("[bundle]\nsource={}\nsubdir={}\n\n", bundle.source, bundle.subdir));
    }
    for volume in volumes {
        if volume.is_esp {
            continue;
        }
        let Some(id) = volume.c_uuid() else {
            continue;
        };
        let text = uuid_text(id);
        let selected = config
            .mounts
            .iter()
            .filter(|m| {
                m.source
                    .strip_prefix("UUID=")
                    .is_some_and(|s| uuid(s).ok() == Some(id))
            })
            .max_by_key(|m| (m.drive == Some(b'C'), m.drive.is_some()))
            .cloned();
        let home = volume.evidence(boot).dos_home;
        let label = alloc::format!(
            "{} {} {}M",
            volume.volume.disk().name(),
            volume.name(),
            volume.volume.sectors / 2048
        );
        crate::compact_println!("Mount candidate: {} UUID={}", label.as_str(), text.as_str());
        editor.volumes.push(EditorVolume {
            volume: *volume,
            home,
            id: text,
            label,
            original_name: selected.as_ref().map(|m| m.name.clone()),
            selected,
            mounted: None,
            volatile: false,
        });
    }
    editor.status = "Export; copy to boot medium".into();
}

pub fn editor_count() -> usize {
    EDITOR.lock().volumes.len()
}

pub fn clear_active_mounts() {
    for volume in &mut EDITOR.lock().volumes {
        volume.mounted = None;
        volume.volatile = false;
    }
}

pub fn editor_line(item: usize) -> String {
    let editor = EDITOR.lock();
    if item == 0 {
        return "Mount setup (staged)".into();
    }
    let index = (item - 1) / 2;
    if let Some(volume) = editor.volumes.get(index) {
        return if (item - 1).is_multiple_of(2) {
            alloc::format!(
                "{} {}",
                volume.label,
                volume
                    .selected
                    .as_ref()
                    .and_then(|m| m.drive)
                    .map_or("off".into(), |d| alloc::format!("{}:", d as char))
            )
        } else {
            alloc::format!(
                "Access {} {}",
                volume.selected.as_ref().map_or("off", |m| match m.access {
                    Access::Ro => "ro",
                    Access::Rw => "rw",
                    Access::Ram => "ram",
                }),
                volume.id
            )
        };
    }
    let footer = item - (1 + editor.volumes.len() * 2);
    match footer {
        0 => editor
            .volumes
            .get(editor.destination)
            .map_or("No export disk".into(), |v| {
                alloc::format!("Export to {}", v.label)
            }),
        1 => "Export BOOT.INI".into(),
        _ => editor.status.clone(),
    }
}

pub fn editor_adjust(item: usize, forward: bool) {
    let mut editor = EDITOR.lock();
    if item == 1 + editor.volumes.len() * 2 {
        if !editor.volumes.is_empty() {
            editor.destination = (editor.destination
                + if forward { 1 } else { editor.volumes.len() - 1 })
                % editor.volumes.len();
        }
        return;
    }
    if item == 0 {
        return;
    }
    let index = (item - 1) / 2;
    let Some(volume) = editor.volumes.get_mut(index) else {
        return;
    };
    if (item - 1).is_multiple_of(2) {
        let choices = b"\0CEFGIJKLMNOPQRSTUVWXYZ";
        let drive = volume.selected.as_ref().and_then(|m| m.drive).unwrap_or(0);
        let old = choices.iter().position(|d| *d == drive).unwrap_or(0);
        let next = (old + if forward { 1 } else { choices.len() - 1 }) % choices.len();
        let drive = choices[next];
        if drive == 0 {
            volume.selected = None;
            return;
        }
        if let Some(mount) = volume.selected.as_mut() {
            mount.drive = Some(drive);
        } else {
            volume.selected = Some(Mount {
                name: alloc::format!("volume{}", index + 1),
                source: alloc::format!("UUID={}", volume.id),
                path: if drive == b'C' {
                    "/home/retroos".into()
                } else {
                    alloc::format!("/disk{}", index + 1)
                },
                subdir: if drive == b'C' && !volume.home.is_empty() {
                    alloc::format!(
                        "/{}",
                        core::str::from_utf8(&volume.home)
                            .unwrap_or("")
                            .trim_end_matches('/')
                    )
                } else {
                    "/".into()
                },
                grant: if volume.home.is_empty() {
                    "/".into()
                } else {
                    alloc::format!(
                        "/{}",
                        core::str::from_utf8(&volume.home)
                            .unwrap_or("")
                            .trim_end_matches('/')
                    )
                },
                drive: Some(drive),
                access: Access::Ro,
                format: "auto".into(),
                partition: None,
            });
        }
    } else if let Some(mount) = volume.selected.as_mut() {
        mount.access = match (mount.access, forward) {
            (Access::Ro, true) | (Access::Ram, false) => Access::Rw,
            (Access::Rw, true) | (Access::Ro, false) => Access::Ram,
            _ => Access::Ro,
        };
    }
}

fn render_mount(out: &mut String, mount: &Mount) {
    out.push_str(&alloc::format!(
        "\n[mount \"{}\"]\nsource={}\npath={}\naccess={}\n",
        mount.name,
        mount.source,
        mount.path,
        match mount.access {
            Access::Ro => "ro",
            Access::Rw => "rw",
            Access::Ram => "ram",
        }
    ));
    if let Some(drive) = mount.drive {
        out.push_str(&alloc::format!("drive={}\n", drive as char));
    }
    if mount.subdir != "/" {
        out.push_str(&alloc::format!("subdir={}\n", mount.subdir));
    }
    if mount.grant != "/" {
        out.push_str(&alloc::format!("grant={}\n", mount.grant));
    }
    if mount.format != "auto" {
        out.push_str(&alloc::format!("format={}\n", mount.format));
    }
    if let Some(partition) = mount.partition {
        out.push_str(&alloc::format!("partition={}\n", partition));
    }
}

pub fn editor_export() {
    let mut editor = EDITOR.lock();
    let volatile = editor.protected
        || editor
            .volumes
            .get(editor.destination)
            .is_some_and(|v| v.volatile);
    let result = export_editor(&mut editor);
    editor.status = match result {
        Ok(path) => alloc::format!(
            "Saved {}{}",
            path,
            if volatile { " (RAM only)" } else { "" }
        ),
        Err(e) => e.into(),
    };
    crate::compact_println!("Mount setup: {}", editor.status.as_str());
}

fn export_editor(editor: &mut Editor) -> Result<String, &'static str> {
    let volume = editor
        .volumes
        .get(editor.destination)
        .ok_or("No export disk")?;
    let config = editor.config.as_ref().ok_or("No boot configuration")?;
    let mut out = editor.settings.clone();
    let selected: Vec<_> = editor
        .volumes
        .iter()
        .filter_map(|v| v.selected.as_ref())
        .collect();
    for mount in &config.mounts {
        // Edit the selected drive view; retain other views of that volume,
        // notably Linux / and C: sharing an ext4 filesystem.
        if editor.volumes.iter().any(|v| v.original_name.as_deref() == Some(&mount.name)) {
            continue;
        }
        if mount
            .drive
            .is_some_and(|d| selected.iter().any(|m| m.drive == Some(d)))
        {
            continue;
        }
        render_mount(&mut out, mount);
    }
    for mount in selected {
        render_mount(&mut out, mount);
    }
    Config::parse_boot(out.as_bytes())?;
    let target = if let Some(prefix) = volume.mounted {
        prefix
    } else {
        let fs = {
            let _guard = vfs::serialize_fs();
            Box::leak(open(volume.volume, Access::Rw, editor.protected)?)
                as &'static dyn vfs::Filesystem
        };
        let target = prefix(&alloc::format!("/mount-export/{}", editor.destination));
        if editor.protected {
            vfs::mount(target, fs);
        } else {
            volume.volume.mount_writable(target, fs, &volume.home);
        }
        vfs::hide_mount(target);
        editor.volumes[editor.destination].mounted = Some(target);
        target
    };
    let volume = &editor.volumes[editor.destination];
    let path = [target, &volume.home, b"BOOT.INI"].concat();
    let handle = vfs::create_to_handle(&path);
    if handle < 0 {
        return Err("Export directory is not writable");
    }
    let Some(file) = vfs::open_backing(&path) else {
        vfs::close_vfs_handle(handle);
        return Err("Cannot open export file");
    };
    let result = {
        let _guard = vfs::serialize_fs();
        let n = file.write_at(0, out.as_bytes());
        let flushed = file.flush();
        file.close();
        if n != out.len() as i32 || flushed != 0 {
            Err("Export write failed")
        } else {
            Ok(())
        }
    };
    vfs::close_vfs_handle(handle);
    result?;
    Ok(alloc::format!(
        "/{}BOOT.INI",
        core::str::from_utf8(&volume.home).unwrap_or("")
    ))
}

pub fn record_mount(id: arch_abi::VolumeUuid, prefix: &'static [u8], volatile: bool) {
    if let Some(volume) = EDITOR
        .lock()
        .volumes
        .iter_mut()
        .find(|v| uuid(&v.id).ok() == Some(id))
    {
        volume.mounted = Some(prefix);
        volume.volatile = volatile;
    }
}
