load("@rules_nasm//nasm:defs.bzl", "nasm_library")
load("//toolchain:os2_watcom.bzl", "os2_dll")

nasm_library(
    name = "pmwin_obj",
    srcs = ["pmwin.asm"],
    copts = ["-fobj"],
)

os2_dll(
    name = "pmwin_dll",
    obj = ":pmwin_obj",
    out = "PMWIN.DLL",
    module_name = "PMWIN",
    exports = [
        "WinBeginPaint.703",
        "WinCreateMsgQueue.716",
        "WinDestroyMsgQueue.726",
        "WinDestroyWindow.728",
        "WinDismissDlg.729",
        "WinDrawBitmap.730",
        "WinDrawBorder.731",
        "WinEndPaint.738",
        "WinFillRect.743",
        "WinGetPS.757",
        "WinInitialize.763",
        "WinInvalidateRect.765",
        "WinLoadString.781",
        "WinMessageBox.789",
        "WinPtInRect.797",
        "WinQueryDlgItemText.815",
        "WinQuerySysValue.829",
        "WinQueryWindow.834",
        "WinQueryWindowPos.837",
        "WinQueryWindowRect.840",
        "WinReleasePS.848",
        "WinSetDlgItemText.859",
        "WinSetWindowPos.875",
        "WinShowWindow.883",
        "WinStartTimer.884",
        "WinStopTimer.885",
        "WinTerminate.888",
        "WinWindowFromID.899",
        "WinPostQueueMsg.902",
        "WinSendDlgItemMsg.903",
        "WinCreateStdWindow.908",
        "WinCreateWindow.909",
        "WinDefDlgProc.910",
        "WinDefWindowProc.911",
        "WinDispatchMsg.912",
        "WinGetMsg.915",
        "WinSendMsg.920",
        "WinDlgBox.923",
        "WinRegisterClass.926",
        "RetroWndProcReturn",
    ],
    visibility = ["//visibility:public"],
)
