load("@rules_nasm//nasm:defs.bzl", "nasm_library")
load("//toolchain:windows_watcom.bzl", "windows_dll")

nasm_library(
    name = "user32_obj",
    srcs = ["user32.asm"],
    copts = ["-fwin32"],
)

windows_dll(
    name = "user32_dll",
    obj = ":user32_obj",
    out = "USER32.DLL",
    module_name = "USER32",
    exports = [
        "AdjustWindowRect", "BeginPaint", "CharUpperA", "CheckMenuItem",
        "CreateWindowExW", "DefWindowProcW", "DestroyIcon", "DialogBoxParamW",
        "DispatchMessageW", "DrawEdge", "EndDialog", "EndPaint", "FillRect",
        "GetClientRect", "GetDC", "GetDlgItem", "GetDlgItemInt",
        "GetDlgItemTextW", "GetMenuItemRect", "GetMessageW", "GetSysColorBrush",
        "GetSystemMetrics", "InflateRect", "InvalidateRect", "KillTimer",
        "LoadAcceleratorsW", "LoadCursorW", "LoadIconW", "LoadMenuW",
        "LoadStringW", "MapWindowPoints", "MessageBoxW", "MoveWindow",
        "OffsetRect", "PeekMessageW", "PostMessageW", "PostQuitMessage",
        "PtInRect", "RegisterClassW", "RetroWndProcReturn", "ReleaseCapture", "ReleaseDC",
        "SendMessageW", "SetCapture", "SetDlgItemInt", "SetDlgItemTextW",
        "SetMenu", "SetRect", "SetTimer", "ShowWindow", "TranslateAcceleratorW",
        "TranslateMessage", "UpdateWindow",
    ],
    visibility = ["//visibility:public"],
)
