load("@rules_rust//rust:defs.bzl", "rust_library")
load("//toolchain:panic.bzl", "panic_strategy")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "klog",
    srcs = ["src/lib.rs"],
    crate_name = "klog",
    edition = "2024",
    rustc_flags = [
        "-Crelocation-model=static",
    ] + panic_strategy(),
)
