load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "klog",
    srcs = ["src/lib.rs"],
    crate_name = "klog",
    edition = "2024",
    rustc_flags = [
        "-Cpanic=abort",
        "-Crelocation-model=static",
    ],
)
